apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism-demo
  labels:
    app: prism-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prism-demo
  template:
    metadata:
      labels:
        app: prism-demo
    spec:
      containers:
      - name: prism-demo
        image: peterbb148/prism-demo
        ports:
        - containerPort: 4010
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: prism-demo
                  resource: requests.cpu
            - name: MY_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: prism-demo
                  resource: limits.cpu
            - name: MY_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: prism-demo
                  resource: requests.memory
            - name: MY_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: prism-demo
                  resource: limits.memory
---
apiVersion: v1
kind: Service
metadata:
  name: prism-demo-service
spec:
  selector:
    app: prism-demo
  ports:
    - protocol: TCP
      port: 4010
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prism-demo-ingress
  annotations:
    kubernetes.io/ingress-class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: prism-demo-service
          servicePort: 4010